from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from ..db import get_session
from ..models import ForkSuggestion, UseCase
from ..services import github
from ..services.artifacts import artifact_path
from ..services.fork_engine import generate_suggestion

router = APIRouter(prefix="/fork-suggestions", tags=["forks"])


class SuggestIn(BaseModel):
    use_case_slug: str
    extra_context: str = ""
    config_kind: str = "yaml"  # yaml|ts


@router.post("")
async def create_suggestion(body: SuggestIn, session: AsyncSession = Depends(get_session)):
    uc = (await session.execute(
        select(UseCase).where(UseCase.slug == body.use_case_slug))).scalar_one_or_none()
    if not uc:
        raise HTTPException(404, "unknown use case")
    result = await generate_suggestion(session, uc, body.extra_context, body.config_kind)
    if "error" in result:
        raise HTTPException(422, result["error"])
    fs = ForkSuggestion(use_case_id=uc.id, base_repo_id=result["base_repo_id"],
                        base_repo_full_name=result["base_repo_full_name"],
                        rationale=result["rationale"],
                        suggested_changes=result["suggested_changes"],
                        suggested_config=result["suggested_config"],
                        config_kind=result["config_kind"])
    session.add(fs)
    await session.commit()
    return {"id": fs.id, **result}


@router.get("")
async def list_suggestions(session: AsyncSession = Depends(get_session)):
    rows = (await session.execute(
        select(ForkSuggestion).order_by(ForkSuggestion.created_at.desc()))).scalars().all()
    return [{"id": f.id, "use_case_id": f.use_case_id, "base_repo": f.base_repo_full_name,
             "status": f.status, "config_kind": f.config_kind, "rationale": f.rationale,
             "suggested_changes": f.suggested_changes, "suggested_config": f.suggested_config,
             "fork_url": f.fork_url, "pr_url": f.pr_url} for f in rows]


@router.get("/artifacts/download")
async def download_artifact(filename: str):
    """Download a generated config artifact for use in a manufactured PR."""
    try:
        config_path = artifact_path(filename)
    except FileNotFoundError:
        raise HTTPException(404, "config artifact not found")
    return FileResponse(config_path, filename=config_path.name,
                        media_type="application/octet-stream")


@router.post("/{suggestion_id}/execute")
async def execute(suggestion_id: int, session: AsyncSession = Depends(get_session)):
    fs = await session.get(ForkSuggestion, suggestion_id)
    if not fs:
        raise HTTPException(404)
    uc = await session.get(UseCase, fs.use_case_id)
    config_path = ".coderabbit.yaml" if fs.config_kind == "yaml" else ".coderabbit/review.ts"
    files = [{"path": c["path"], "content": c.get("content", "")} for c in fs.suggested_changes]
    files.append({"path": config_path, "content": fs.suggested_config})
    try:
        result = await github.fork_and_open_pr(
            base_full_name=fs.base_repo_full_name,
            branch=f"demo/{uc.slug}-{fs.id}",
            files=files,
            pr_title=f"Demo: {uc.name}",
            pr_body=(f"Manufactured demo PR for CodeRabbit use case **{uc.name}**.\n\n"
                     f"{fs.rationale}\n\n_Generated by coderabbit-demo finder._"),
        )
    except Exception as exc:  # surfaces token/permission problems cleanly
        fs.status = "failed"
        await session.commit()
        raise HTTPException(502, f"fork/PR failed: {exc}")
    fs.status, fs.fork_url, fs.pr_url = "pr_opened", result["fork_url"], result["pr_url"]
    await session.commit()
    return result
